export {
  addFlowEdge,
  analyzeExecutionTopology,
  incomingStructuralEdges,
  independentStructuralSuccessorTaskIds,
  isDerivedBranchingGoal,
  outgoingStructuralEdges,
  reachableStructuralTaskIds,
  uniqueIncomingStructuralTaskIds,
  uniqueOutgoingStructuralTaskIds,
  validateFlowGraph,
  type ExecutionDependencyEdge,
  type ExecutionDependencyKind,
  type ExecutionTopologyAnalysis,
  type FlowEdge,
  type FlowGraph,
  type FlowInvariantError,
  type FlowInvariantErrorCode,
  type ReferenceFlowEdge,
  type StructuralFlowEdge,
  type StructuralFlowKind,
} from './domain/flow';

export {
  buildTaskExecutionReadModels,
  deriveManualCompletionControl,
  deriveTaskCompletionAvailability,
  evaluateDerivedGoalStatuses,
  normalizeExecutionStatuses,
  type ExecutionStatusChange,
  type ExecutionStatusNormalization,
  type ExecutionStatusNormalizationReason,
  type GoalEvaluation,
  type ManualCompletionControl,
  type TaskCompletionAvailability,
  type TaskExecutionReadModel,
} from './domain/execution';
